package com.hospital.service;

import com.hospital.entity.Document;
import com.hospital.entity.PreConsultation;
import com.hospital.integration.ai.AiProvider;
import com.hospital.repository.DocumentRepository;
import com.hospital.repository.PreConsultationRepository;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class PatientSummaryService {

    private final MedicalDocumentSummarizationService documentSummarizationService;
    private final AiProvider aiProvider;
    private final DocumentRepository documentRepository;
    private final PreConsultationRepository preConsultationRepository;

    public PatientSummaryService(
            MedicalDocumentSummarizationService documentSummarizationService,
            AiProvider aiProvider,
            DocumentRepository documentRepository,
            PreConsultationRepository preConsultationRepository) {
        this.documentSummarizationService = documentSummarizationService;
        this.aiProvider = aiProvider;
        this.documentRepository = documentRepository;
        this.preConsultationRepository = preConsultationRepository;
    }

    /**
     * Generates a single, consolidated AI summary combining both the pre-consultation intake
     * and any uploaded medical documents.
     *
     * @param appointmentId The ID of the appointment.
     * @param patientId The ID of the patient.
     * @return The final consolidated patient summary.
     */
    @org.springframework.cache.annotation.Cacheable(value = "patient_summaries", key = "#appointmentId")
    public String getFinalConsolidatedSummary(Long appointmentId, Long patientId) {
        // 1. Fetch pre-consultation summary (Already generated by General AI during completePreConsultation)
        String preConsultationSummary = "No pre-consultation data available.";
        PreConsultation pc = preConsultationRepository.findByAppointment_Id(appointmentId).orElse(null);
        if (pc != null && pc.getAiSummary() != null) {
            preConsultationSummary = pc.getAiSummary();
        }

        // 2. Fetch recent patient documents and combine their existing AI summaries
        List<Document> patientDocuments = documentRepository.findByPatientIdAndStatus(patientId, "ACTIVE");
        StringBuilder documentsCombinedText = new StringBuilder();
        
        for (Document doc : patientDocuments) {
            documentsCombinedText.append("Document: ").append(doc.getFileName()).append(" (").append(doc.getDocumentType()).append(")\n");
            if (doc.getAiSummary() != null && !doc.getAiSummary().isEmpty()) {
                documentsCombinedText.append(doc.getAiSummary()).append("\n\n");
            } else {
                documentsCombinedText.append("No summary available for this document.\n\n");
            }
        }

        String medicalDocumentsSummary = documentsCombinedText.length() > 0 ? documentsCombinedText.toString() : "No medical documents available.";

        // 3. Consolidate both summaries using the General AI to organize them into the final structured format
        return consolidateSummaries(preConsultationSummary, medicalDocumentsSummary);
    }

    private String consolidateSummaries(String preConsultationSummary, String medicalDocumentsSummary) {
        String prompt = "You are a clinical assistant. Consolidate the following two summaries into one clear, structured doctor-facing summary.\n" +
                "Do not duplicate information. You MUST format your response exactly using these bullet points:\n" +
                "• Summary: [Patient background, relevant history, and main concerns]\n" +
                "• Symptoms: [Current symptoms from pre-consultation]\n" +
                "• Potential Diagnosis/Impression: [Existing medical conditions and possible diagnosis]\n" +
                "• Current Medications: [List of current medications]\n" +
                "• Lab Values Mentioned: [Important laboratory findings from medical documents]\n\n" +
                "--- PRE-CONSULTATION SUMMARY ---\n" + preConsultationSummary + "\n\n" +
                "--- MEDICAL DOCUMENTS SUMMARY ---\n" + medicalDocumentsSummary;

        // Use the general AI (Gemini) for the final orchestration and formatting
        return aiProvider.generateStructuredSummary(prompt);
    }
}
