package com.hospital.service;

import com.hospital.entity.Document;
import com.hospital.entity.PreConsultation;
import com.hospital.integration.ai.AiProvider;
import com.hospital.repository.DocumentRepository;
import com.hospital.repository.PreConsultationRepository;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class PatientSummaryService {

    private final MedicalDocumentSummarizationService documentSummarizationService;
    private final AiProvider aiProvider;
    private final DocumentRepository documentRepository;
    private final PreConsultationRepository preConsultationRepository;

    public PatientSummaryService(
            MedicalDocumentSummarizationService documentSummarizationService,
            AiProvider aiProvider,
            DocumentRepository documentRepository,
            PreConsultationRepository preConsultationRepository) {
        this.documentSummarizationService = documentSummarizationService;
        this.aiProvider = aiProvider;
        this.documentRepository = documentRepository;
        this.preConsultationRepository = preConsultationRepository;
    }

    /**
     * Generates a final consolidated summary for the doctor dashboard.
     * This combines the medical documents summary (using the custom Qwen model)
     * and the pre-consultation summary (using the general Gemini AI).
     *
     * @param appointmentId The ID of the appointment.
     * @param patientId The ID of the patient.
     * @return The final consolidated patient summary.
     */
    public String getFinalConsolidatedSummary(Long appointmentId, Long patientId) {
        // 1. Fetch pre-consultation summary (Already generated by General AI during completePreConsultation)
        String preConsultationSummary = "No pre-consultation data available.";
        PreConsultation pc = preConsultationRepository.findByAppointment_Id(appointmentId).orElse(null);
        if (pc != null && pc.getAiSummary() != null) {
            preConsultationSummary = pc.getAiSummary();
        }

        // 2. Fetch recent patient documents and summarize them using the custom model
        List<Document> patientDocuments = documentRepository.findByPatientIdAndStatus(patientId, "ACTIVE");
        StringBuilder documentsCombinedText = new StringBuilder();
        
        for (Document doc : patientDocuments) {
            // Ideally, you would extract text from the file (PDF/Image) using OCR here.
            // For example, calling AWS Textract or Tesseract OCR on doc.getStoragePath()
            String extractedText = "[Simulated OCR text from " + doc.getFileName() + " (" + doc.getDocumentType() + ")]";
            documentsCombinedText.append("Document: ").append(doc.getFileName()).append("\n");
            documentsCombinedText.append(extractedText).append("\n\n");
        }

        String medicalDocumentsSummary = "No medical documents available.";
        if (documentsCombinedText.length() > 0) {
            // Call the custom fine-tuned model for document summarization
            medicalDocumentsSummary = documentSummarizationService.summarizeDocument(documentsCombinedText.toString());
        }

        // 3. Consolidate both summaries using the General AI to organize them into the final structured format
        return consolidateSummaries(preConsultationSummary, medicalDocumentsSummary);
    }

    private String consolidateSummaries(String preConsultationSummary, String medicalDocumentsSummary) {
        String prompt = "You are a clinical assistant. Consolidate the following two summaries into one clear, structured doctor-facing summary.\n" +
                "Do not duplicate information. Organize by:\n" +
                "- Patient background\n" +
                "- Existing medical conditions\n" +
                "- Current symptoms (from pre-consultation)\n" +
                "- Important laboratory findings (from medical documents)\n" +
                "- Current medications\n" +
                "- Relevant medical history\n" +
                "- Patient-reported concerns\n" +
                "- Information requiring physician attention\n\n" +
                "--- PRE-CONSULTATION SUMMARY ---\n" + preConsultationSummary + "\n\n" +
                "--- MEDICAL DOCUMENTS SUMMARY ---\n" + medicalDocumentsSummary;

        // Use the general AI (Gemini) for the final orchestration and formatting
        return aiProvider.generateStructuredSummary(prompt);
    }
}
