spring.application.name=hospital-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hospital_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

app.demo-mode=${DEMO_MODE}
server.port=${PORT:8080}
server.address=0.0.0.0
groq.api.key=${GROQ_API_KEY}
spring.threads.virtual.enabled=true





# Supabase Storage Configurations
supabase.storage.endpoint=${SUPABASE_STORAGE_ENDPOINT:}
supabase.storage.region=${SUPABASE_STORAGE_REGION:}
supabase.storage.access-key=${SUPABASE_STORAGE_ACCESS_KEY:}
supabase.storage.secret-key=${SUPABASE_STORAGE_SECRET_KEY:}
supabase.storage.bucket=${SUPABASE_STORAGE_BUCKET:hospital-medical-documents}

# Multipart upload config
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=55MB
